# functions

function(add_lib0 name srcstr depstr)
	message(STATUS "[add_lib] name=${name}, srcstr=${srcstr}, depstr=${depstr}")
  string(REGEX MATCHALL "[^ ;]+" srcs "${srcstr}")
  string(REGEX MATCHALL "[^ ;]+" deps "${depstr}")
	message(STATUS "srcs=${srcs}")
	message(STATUS "deps=${deps}")
	add_library(${name} ${srcs})
endfunction()	

function(add_lib name srcstr)
  set(deps ${ARGV})
  message(STATUS "[add_lib] name=${name}, deps=${deps}, ARGC=${ARGC}, ARGV=${ARGV}")
  string(REGEX MATCHALL "[^ ;]+" srcs "${srcstr}")
  list(REMOVE_AT deps 0 1)
  message(STATUS "[add_lib] name=${name}, deps=${deps}")
	add_library(${name} ${srcs})
  if (${ARGC} EQUAL 2)
    target_link_libraries(${name} ${basic_libs})
  else()
    string(REGEX MATCHALL "[^ ;]+" deps "${ARGV2}")
    target_link_libraries(${name} ${deps} ${basic_libs})
  endif()
endfunction()	

function(add_bin name)
  set(deps ${ARGV})
  #message(STATUS "[add_bin] name=${name}, deps=${deps}, ARGC=${ARGC}, ARGV=${ARGV}")
  list(REMOVE_AT deps 0)
  message(STATUS "[add_bin] name=${name}, deps=${deps}")
	add_executable(${name} ${name})
  if (${ARGC} EQUAL 1)
    target_link_libraries(${name} ${basic_libs})
  else()
    string(REGEX MATCHALL "[^ ;]+" deps "${ARGV1}")
    target_link_libraries(${name} ${deps} ${basic_libs})
  endif()
endfunction()	

function(add_test0 name depstr)
	message(STATUS "[add_test] name=${name}")
  string(REGEX MATCHALL "[^ ;]+" deps "${depstr}")
  string(LENGTH depstr depstr_len)
	message(STATUS "deps=${deps}, depstr_len=${depstr_len}")
  set(srcs ${name} ${src_dir}/test_main.cpp)
	add_executable(${name} ${srcs})
	target_link_libraries(${name} gtest ${deps} ${basic_libs})
endfunction()	

function(add_test name)
  set(deps ${ARGV})
  #message(STATUS "[add_bin] name=${name}, deps=${deps}, ARGC=${ARGC}, ARGV=${ARGV}")
  list(REMOVE_AT deps 0)
  message(STATUS "[add_test] name=${name}, deps=${deps}")
  set(srcs ${name} ${src_dir}/test_main.cpp)
	add_executable(${name} ${srcs})
  set(test_libs gtest ${basic_libs})
  if (${ARGC} EQUAL 1)
    target_link_libraries(${name} ${test_libs})
  else()
    string(REGEX MATCHALL "[^ ;]+" deps "${ARGV1}")
    target_link_libraries(${name} ${deps} ${test_libs})
  endif()
endfunction()	

